#!/usr/bin/env python3
"""Extract first-page text from each session PDF to seed manifest titles.

Run once to populate `manifest.yaml`. The user is expected to read each
suggested title and refine it; whatever you put in `manifest.yaml` is
authoritative — `tools/build_units.py` doesn't re-read PDFs.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Iterable

import pypdf

ROOT = Path(__file__).resolve().parent.parent
PDF_DIR = ROOT / "pdfs"


def first_page_lines(pdf_path: Path, *, n_lines: int = 8) -> list[str]:
    """Return the first non-blank ``n_lines`` lines from page 1."""
    try:
        reader = pypdf.PdfReader(str(pdf_path))
    except Exception as exc:
        return [f"<pypdf failed: {exc}>"]
    if not reader.pages:
        return []
    raw = reader.pages[0].extract_text() or ""
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]
    return lines[:n_lines]


def guess_title(lines: Iterable[str]) -> str:
    """Pick a one-line title from the first-page lines.

    Heuristic: skip metadata-ish lines (date, author, page numbers,
    "Worksheet", "Answers"), return the first remaining line. The user
    edits the YAML afterwards anyway, so a wrong guess is cheap.
    """
    skip = re.compile(
        r"^(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|"          # dates: 3-4-19, 11/18/19
        r"page\s*\d+|"                                # page numbers
        r"sharon\s+hargus|"                           # author
        r"witsuwit'?en\s+literacy(\s+\d)?|"          # course header
        r"worksheet|answers?\s+key|answers?|"        # sheet kind
        r"name[:\s]|date[:\s])",                     # form fields
        re.IGNORECASE,
    )
    for ln in lines:
        if skip.match(ln):
            continue
        # Trim trailing punctuation / page numbers, collapse internal whitespace.
        ln = re.sub(r"\s+", " ", ln).strip(" .;:")
        if 4 <= len(ln) <= 120:
            return ln
    return ""


def main() -> int:
    if not PDF_DIR.exists():
        print(f"ERROR: {PDF_DIR} not found", file=sys.stderr)
        return 1
    print(f"# generated by tools/extract_titles.py — REVIEW AND EDIT")
    print()
    for course in (1, 2):
        course_dir = PDF_DIR / f"literacy_{course}"
        # Only handouts / worksheets carry a title; answers reuse the
        # worksheet's title.
        suffix = "_handout.pdf" if course == 1 else "_worksheet.pdf"
        pdfs = sorted(p for p in course_dir.glob(f"*{suffix}"))
        print(f"## Literacy {course}")
        for p in pdfs:
            lines = first_page_lines(p)
            title = guess_title(lines)
            print(f"\n# {p.name}")
            for i, ln in enumerate(lines, 1):
                print(f"#   L{i}: {ln}")
            print(f"#   → guess: {title}")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
